import React, { useEffect, useState } from "react";
import { AgentActionItem } from "../lib/types";
import { fetchAgentActions } from "../lib/api";
import { formatDate } from "../lib/formatters";
import { LoadingState } from "./LoadingState";

interface ActionsViewProps {
  merchantId: number;
}

export function ActionsView({ merchantId }: ActionsViewProps) {
  const [actions, setActions] = useState<AgentActionItem[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const [filterStatus, setFilterStatus] = useState<string>("ALL");

  useEffect(() => {
    let isMounted = true;
    async function loadActions() {
      setLoading(true);
      setError(null);
      try {
        const data = await fetchAgentActions(merchantId, 100);
        if (isMounted) setActions(data);
      } catch (err: unknown) {
        if (isMounted) {
          setError(err instanceof Error ? err.message : "Failed to load actions");
        }
      } finally {
        if (isMounted) setLoading(false);
      }
    }
    loadActions();
    return () => {
      isMounted = false;
    };
  }, [merchantId]);

  const filteredActions = actions.filter((a) => {
    if (filterStatus === "ALL") return true;
    if (filterStatus === "PENDING") {
      return (
        a.approval_status === "REQUIRED" ||
        a.approval_status === "PENDING" ||
        a.execution_status === "PENDING"
      );
    }
    if (filterStatus === "APPROVED") {
      return a.policy_status === "APPROVED" || a.approval_status === "APPROVED";
    }
    if (filterStatus === "BLOCKED") {
      return a.policy_status === "BLOCKED" || a.approval_status === "REJECTED";
    }
    return true;
  });

  const getPolicyBadge = (status: string) => {
    if (status === "APPROVED" || status === "ALLOWED") {
      return (
        <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-semibold bg-emerald-50 text-emerald-700 border border-emerald-200">
          <span className="w-1.5 h-1.5 rounded-full bg-emerald-500"></span>
          Policy Passed
        </span>
      );
    }
    return (
      <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-semibold bg-rose-50 text-rose-700 border border-rose-200">
        <span className="w-1.5 h-1.5 rounded-full bg-rose-500"></span>
        Policy Blocked
      </span>
    );
  };

  const getApprovalBadge = (status: string) => {
    if (status === "REQUIRED" || status === "PENDING") {
      return (
        <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-semibold bg-amber-50 text-amber-700 border border-amber-200">
          <span className="w-1.5 h-1.5 rounded-full bg-amber-500"></span>
          Approval Required
        </span>
      );
    }
    if (status === "APPROVED" || status === "NOT_REQUIRED") {
      return (
        <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-medium bg-slate-100 text-slate-700">
          {status === "NOT_REQUIRED" ? "Auto-Authorized" : "Approved"}
        </span>
      );
    }
    return (
      <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-medium bg-rose-50 text-rose-700">
        Rejected
      </span>
    );
  };

  const getExecutionBadge = (status: string) => {
    switch (status) {
      case "EXECUTED":
      case "SUCCESS":
        return (
          <span className="px-2 py-0.5 rounded text-xs font-medium bg-emerald-100 text-emerald-800">
            EXECUTED
          </span>
        );
      case "SKIPPED":
        return (
          <span className="px-2 py-0.5 rounded text-xs font-medium bg-slate-100 text-slate-600">
            SKIPPED
          </span>
        );
      case "PENDING":
      default:
        return (
          <span className="px-2 py-0.5 rounded text-xs font-medium bg-amber-100 text-amber-800">
            PENDING
          </span>
        );
    }
  };

  return (
    <div className="space-y-6">
      {/* Policy Governance Explanatory Card */}
      <div className="bg-white rounded-xl border border-slate-200 p-6 shadow-sm">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-amber-500"></span>
              <h3 className="text-base font-bold text-slate-900">
                Agent Actions & Approval Gating
              </h3>
            </div>
            <p className="text-xs text-slate-500 max-w-2xl leading-relaxed">
              Every action generated by the Revora Growth Agent is bounded by safety guardrails.
              High-impact operations (discount offers, retry payments, automated nudges) require explicit merchant authorization before execution.
            </p>
          </div>

          <div className="flex items-center gap-2 bg-slate-50 border border-slate-200 rounded-lg p-1 text-xs">
            {["ALL", "PENDING", "APPROVED", "BLOCKED"].map((tab) => (
              <button
                key={tab}
                onClick={() => setFilterStatus(tab)}
                className={`px-3 py-1.5 rounded-md font-semibold transition-colors cursor-pointer ${
                  filterStatus === tab
                    ? "bg-slate-900 text-white shadow-xs"
                    : "text-slate-600 hover:text-slate-900"
                }`}
              >
                {tab}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Actions Table */}
      <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
        {loading ? (
          <LoadingState message="Fetching agent actions and approval status..." />
        ) : error ? (
          <div className="p-8 text-center text-rose-600 text-sm">{error}</div>
        ) : filteredActions.length === 0 ? (
          <div className="p-12 text-center text-slate-500 text-sm">
            No actions found matching the current filter.
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-slate-50/75 border-b border-slate-200 text-[11px] font-semibold uppercase tracking-wider text-slate-500">
                  <th className="py-3.5 px-5">Action & Context</th>
                  <th className="py-3.5 px-4">Customer</th>
                  <th className="py-3.5 px-4">Expected Impact</th>
                  <th className="py-3.5 px-4">Policy Status</th>
                  <th className="py-3.5 px-4">Approval Gating</th>
                  <th className="py-3.5 px-4">Execution</th>
                  <th className="py-3.5 px-5 text-right">Created At</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 text-sm">
                {filteredActions.map((action) => (
                  <tr key={action.id} className="hover:bg-slate-50/50 transition-colors">
                    <td className="py-3.5 px-5">
                      <div className="flex items-center gap-2">
                        <span className="font-mono text-xs font-bold text-slate-900">
                          #{action.id}
                        </span>
                        <span className="px-2 py-0.5 rounded font-mono text-xs font-semibold bg-slate-100 text-slate-800">
                          {action.action_type}
                        </span>
                      </div>
                      <div className="text-xs text-slate-500 mt-1 line-clamp-1 max-w-sm">
                        {action.reason}
                      </div>
                    </td>

                    <td className="py-3.5 px-4 whitespace-nowrap">
                      <div className="font-medium text-slate-800 text-xs">
                        {action.customer_name}
                      </div>
                      <div className="text-[11px] font-mono text-slate-400">
                        {action.customer_email || `ID: ${action.customer_id}`}
                      </div>
                    </td>

                    <td className="py-3.5 px-4 text-xs font-medium text-slate-700">
                      {action.expected_impact}
                    </td>

                    <td className="py-3.5 px-4 whitespace-nowrap">
                      {getPolicyBadge(action.policy_status)}
                    </td>

                    <td className="py-3.5 px-4 whitespace-nowrap">
                      {getApprovalBadge(action.approval_status)}
                    </td>

                    <td className="py-3.5 px-4 whitespace-nowrap">
                      {getExecutionBadge(action.execution_status)}
                    </td>

                    <td className="py-3.5 px-5 text-right text-xs font-mono text-slate-500 whitespace-nowrap">
                      {formatDate(action.created_at)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        <div className="p-4 bg-slate-50 border-t border-slate-100 flex items-center justify-between text-xs text-slate-500">
          <span>Total Actions: {filteredActions.length}</span>
          <span className="italic">
            Read-only verified log from SQLite table: <code className="font-mono">agent_actions</code>
          </span>
        </div>
      </div>
    </div>
  );
}
